version: 2
jobs:
    build:
        docker:
            - image: mcr.microsoft.com/dotnet/core/sdk:2.1
        steps:
            - checkout
            - run: find .
            - run: 
                name: Restore
                command: dotnet restore
            - run: 
                name: Running Tests
                command: dotnet test test/GradeBook.Tests